Repository IEEE-VIT/back-to-future, pull requests merged in 2022-10, with the labels that each got.

#15 A Binary Search Algorithm using Golang
  Go/binarysearch.go
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#20 Guess the Number
  Python/guessthenumber.py
Labels: enhancement, hacktoberfest-accepted, algorithms, hacktoberfest

#25 Added MergeSort in Java and updated README
  Java/MergeSort.java
  README.md
Labels: hacktoberfest-accepted, algorithms, problem-solving, hacktoberfest

#26 Create Armstrong_no.cpp
  C++/Armstrong_no.cpp
Labels: hacktoberfest-accepted, algorithms, problem-solving, hacktoberfest

#23 Implemented most algos using scala
  Scala/binarysearch.scala
  Scala/binarytree.scala
  Scala/bubblesort.scala
  Scala/checkPrime.scala
  Scala/eval.scala
  Scala/fibonacci.scala
  Scala/heapsort.scala
  Scala/helloworld.scala
  Scala/infixtopostfix.scala
  Scala/linearsearch.scala
  Scala/selectionsort.scala
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#34 Implemented the following in rust
  Rust/binarysearch.rs
  Rust/bubblesort.rs
  Rust/checkprime.rs
  Rust/fibonacci.rs
  Rust/heapsort.rs
  Rust/selectionsort.rs
Labels: hacktoberfest-accepted, algorithms, hacktoberfest

#32 implementation of selectionSort using java
  Java/SelectionSort.java
Labels: hacktoberfest-accepted, algorithms, problem-solving, hacktoberfest

#42 Added several JavaScript programs
  Javascript/armstrong_no.js
  Javascript/fibonacci.js
  Javascript/infixtopostfix.js
Labels: hacktoberfest-accepted, problem-solving, hacktoberfest

#62 implement bubblesort in python
  Python/bubblesort.py
Labels: good first issue, hacktoberfest-accepted, problem-solving, hacktoberfest

#63 implement binarysearch in python
  Python/binarysearch.py
Labels: hacktoberfest-accepted, problem-solving, hacktoberfest

#64 implemented checkPrime in python
  Python/checkPrime.py
Labels: enhancement, hacktoberfest-accepted, problem-solving, hacktoberfest

#65 implemented fibonacci series in python
  Python/fibonacci.py
Labels: hacktoberfest-accepted, problem-solving, hacktoberfest
